//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K309Portfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolioDB : DbContext
    {
        public PortfolioDB()
            : base("name=PortfolioDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutSection> AboutSections { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<PortfolioSection> PortfolioSections { get; set; }
        public virtual DbSet<Section1> Section1 { get; set; }
        public virtual DbSet<sectionTeam> sectionTeams { get; set; }
        public virtual DbSet<ServiceSection> ServiceSections { get; set; }
    }
}
