//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K309Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sectionTeam
    {
        public int id { get; set; }
        public string imageUrl { get; set; }
        public string fullname { get; set; }
        public string workArea { get; set; }
        public string fbLink { get; set; }
        public string instaLink { get; set; }
        public string twitterLink { get; set; }
    }
}
